name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Build Backend Docker image
      run: docker build ./backend --file ./backend/Dockerfile --tag my-backend-image:$(date +%s)
    
    - name: Build Frontend Docker image
      run: docker build ./frontend --file ./frontend/Dockerfile --tag my-frontend-image:$(date +%s)
    
    - name: Build Nginx Docker image
      run: docker build ./nginx --file ./nginx/Dockerfile --tag my-nginx-image:$(date +%s)
