name: CI/CD

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # ==========================================
      # 1. Checkout GitHub repository
      # ==========================================
      - name: Checkout code
        uses: actions/checkout@v4

      # ==========================================
      # 2. Build Backend Docker image
      # ==========================================
      - name: Build Backend Docker image
        run: |
          docker build ./backend \
            --file ./backend/Dockerfile \
            --tag my-backend-image:${{ github.sha }}

      # ==========================================
      # 3. Build Frontend Docker image
      # ==========================================
      - name: Build Frontend Docker image
        run: |
          docker build ./frontend \
            --file ./frontend/Dockerfile \
            --tag my-frontend-image:${{ github.sha }}

      # ==========================================
      # 4. Build Nginx Docker image
      # ==========================================
      - name: Build Nginx Docker image
        run: |
          docker build ./nginx \
            --file ./nginx/Dockerfile \
            --tag my-nginx-image:${{ github.sha }}

      # ==========================================
      # 5. Deploy to AWS EC2
      # ==========================================
      - name: Deploy to EC2
        if: github.event_name == 'push'
        uses: appleboy/ssh-action@v1.2.0
        with:
            host: ${{ secrets.EC2_HOST }}
            username: ubuntu
            key: ${{ secrets.EC2_SSH_KEY }}
            script: |
              set -e

              if [ ! -d "$HOME/Login-Portfolio/.git" ]; then
                echo "First deployment - cloning repository..."
                git clone https://github.com/Vijayaraj26/Login-Portfolio.git "$HOME/Login-Portfolio"
              else
                echo "Existing deployment - getting latest code..."
                cd "$HOME/Login-Portfolio"
                git fetch origin main
                git reset --hard origin/main
              fi

              cd "$HOME/Login-Portfolio"

              echo "Building Docker containers..."
              docker compose build

              echo "Starting Docker containers..."
              docker compose up -d

              echo "Checking containers..."
              docker compose ps